#!/bin/bash

set -e

# Run javascript bench
cd javascript
/usr/bin/time -v node readability.js
cd ..

# Run go bench
cd go
go run readability.go
cd ..

# Run rust bench
cargo bench --bench readability-main

# Run rust bench
cargo bench --bench readability
