#!/bin/bash

set -e

# Run JS bench
cd benches/javascript
/usr/bin/time -v node readability.js
cd ..

# Run go bench
cd benches/go
go run readability.go
cd ..

# Run RS bench
cargo bench --bench readability
